model: "gpt-4o-mini"
language: "English (United States)"
early-access: false
review:
  enabled: true
  tone: "informal"
  ignore:
    label: []
    title: []
    branch: []
  stop-on:
    closed: true
    locked: false
    merged: true
  tools:
    profile: "assertive"
summary:
  enabled: true
  tone: "informal"
  ignore:
    label: []
    title: []
    branch: []
  stop-on:
    closed: true
    locked: false
    merged: true
chat:
  enabled: true
  tone: "informal"
  ignore:
    label: []
    title: []
    branch: []
  stop-on:
    closed: true
    locked: false
    merged: true
  auto: true
